{
 "title": "Kafka Cluster Monitor",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Global Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers Number",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Active Brokers",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"kafka\"} == 1",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In And Out /s (1min)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesInPerSec\",topic=\"\"})",
     "legendFormat": "{{Bytes In 1min}}"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesOutPerSec\",topic=\"\"})",
     "legendFormat": "{{Bytes Out 1min}}"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_fiveminuterate{name=\"BytesInPerSec\",topic=\"\"})",
     "legendFormat": "{{Bytes In 5min}}"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_fiveminuterate{name=\"BytesOutPerSec\",topic=\"\"})",
     "legendFormat": "{{Bytes Out 5min}}"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_fifteenminuterate{name=\"BytesInPerSec\",topic=\"\"})",
     "legendFormat": "{{Bytes In 15min}}"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_fifteenminuterate{name=\"BytesOutPerSec\",topic=\"\"})",
     "legendFormat": "{{Bytes Out 15min}}"
    }
   ]
  },
  {
   "title": "All Topics Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_value{job=\"kafka\",name=\"GlobalTopicCount\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "All Partitions",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_value{job=\"kafka\",name=\"GlobalPartitionCount\"})",
     "legendFormat": "{{All Partitions Count}}"
    },
    {
     "expr": "sum(kafka_controller_kafkacontroller_value{job=\"kafka\",name=\"OfflinePartitionsCount\"})",
     "legendFormat": "{{Offline Partition Count}}"
    }
   ]
  },
  { "title": "Topics Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Topics Bytes In PerSec (5min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum(kafka_server_brokertopicmetrics_fiveminuterate{name=\"BytesInPerSec\",topic!=\"\"}) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Produce Requests /s (5min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum(kafka_server_brokertopicmetrics_fiveminuterate{name=\"TotalProduceRequestsPerSec\",topic!=\"\"}) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topics Bytes Out PerSec (5min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum(kafka_server_brokertopicmetrics_fiveminuterate{name=\"BytesOutPerSec\",topic!=\"\"}) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Fetch Requests /s (5min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum(kafka_server_brokertopicmetrics_fiveminuterate{name=\"TotalFetchRequestsPerSec\",topic!=\"\"}) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topics Messages In PerSec (5min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum(kafka_server_brokertopicmetrics_fiveminuterate{name=\"MessagesInPerSec\",topic!=\"\"}) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Borkers Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Each Broker Bytes In & Out",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesInPerSec\",topic=\"\"}",
       "legendFormat": "Bytes In/s-{{instance}}-1Min"
      },
      {
       "expr": "kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesOutPerSec\",topic=\"\"}",
       "legendFormat": "Bytes Out/s-{{instance}}-1Min"
      },
      {
       "expr": "kafka_server_brokertopicmetrics_fiveminuterate{name=\"BytesInPerSec\",topic=\"\"}",
       "legendFormat": "Bytes In/s-{{instance}}-5Min"
      },
      {
       "expr": "kafka_server_brokertopicmetrics_fiveminuterate{name=\"BytesOutPerSec\",topic=\"\"}",
       "legendFormat": "Bytes Out/s-{{instance}}-5Min"
      },
      {
       "expr": "kafka_server_brokertopicmetrics_fifteenminuterate{name=\"BytesInPerSec\",topic=\"\"}",
       "legendFormat": "Bytes In/s-{{instance}}-15Min"
      },
      {
       "expr": "kafka_server_brokertopicmetrics_fifteenminuterate{name=\"BytesOutPerSec\",topic=\"\"}",
       "legendFormat": "Bytes Out/s-{{instance}}-15Min"
      }
     ]
    },
    {
     "title": "Brokers JVM (G1 Eden Space)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{job=\"kafka\",pool=\"G1 Eden Space\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Brokers JVM (G1 Old Gen)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{job=\"kafka\",pool=\"G1 Old Gen\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Brokers JVM (G1 Survivor Space)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{job=\"kafka\",pool=\"G1 Survivor Space\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Brokers JVM (Code Cache)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{job=\"kafka\",pool=\"Code Cache\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Brokers JVM (Metaspace)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{job=\"kafka\",pool=\"Metaspace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Brokers JVM (Compressed Class Space)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{job=\"kafka\",pool=\"Compressed Class Space\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Broker JVM Memory Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "decbytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Time spent G1 Young Gc (5min)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "percentunit", "label": "% time in GC" }
     ],
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\",gc=\"G1 Young Generation\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Broker CPU Usage (1min)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"kafka\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Time spent G1 Old GC (5min)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\",gc=\"G1 Old Generation\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Gc Count /s (G1 Young Generation)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_count{gc=\"G1 Young Generation\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Brokers Log Flush Rate /Ms",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_log_logflushstats_fiveminuterate{job=\"kafka\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Files open count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{job=\"kafka\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Auto Leader Balance /Ms (5min)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_controller_controllerstats_fiveminuterate{name=\"AutoLeaderBalanceRateAndTimeMs\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}